/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab5 */

#ifndef _Included_Lab5
#define _Included_Lab5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab5
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab5_calculateSTDDev
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Lab5
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab5_calculateMean
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
